### PR TITLE
start working on my first calendar app

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by tandaraelena — APPROVED** [review]
Somebody is working hard here 👍

**Comment by biancalina** [comment]
@tandaraelena I'm trying :D

**Comment by ghost** [comment]
> Somebody is working hard here 👍

@tandaraelena I'm trying :D

**Review by marianzburlea — APPROVED** [review]

**Review by psyhedeliq — APPROVED** [review]
🚀 🚀 🚀 Go, go, go @biancalina ! 🚀 🚀 🚀

**Review by BogdanNegura — APPROVED** [review]

**Review by robertoalx — APPROVED** [review]

**Pull request merged**
